spring.datasource.url=jdbc:postgresql://localhost:5432/momozon
spring.datasource.username=khai
spring.datasource.password=01082006Khai!

spring.jpa.hibernate.ddl-auto=update

# Optional: show generated SQL
# spring.jpa.show-sql=true